name: flutter_xspend
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_sticky_header: ^0.6.5
  flutter_vector_icons: ^2.0.0
  http: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/xpense-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - lib/src/localization/app_en.arb
    - lib/src/localization/app_km.arb
    - .env.development
    - .env.production
  fonts:
    - family: KantumruyPro
      fonts:
        - asset: fonts/KantumruyPro-Regular.ttf
    - family: KantumruyPro-SemiBold
      fonts:
        - asset: fonts/KantumruyPro-SemiBold.ttf
          weight: 700
    - family: KantumruyPro-Bold
      fonts:
        - asset: fonts/KantumruyPro-Bold.ttf
          weight: 900

