final List transactions = [
  {
    'id': '123',
    'amount': 2,
    'currency_type': 'khr',
    'note': 'Coffee',
    'transaction_type': 1,
    'transaction_date': '2_Dec_2023',
    'user_id': 'user1',
    'category_id': 'cat1',
    'synced': true,
    'local_user_id': '1a'
  },
  {
    'id': '124',
    'amount': 6,
    'currency_type': 'khr',
    'note': 'Breads',
    'transaction_type': 1,
    'transaction_date': '2_Dec_2023',
    'user_id': 'user1',
    'category_id': 'cat2',
    'synced': true,
    'local_user_id': '1a'
  },
  {
    'id': '125',
    'amount': 7,
    'currency_type': 'khr',
    'note': 'Soda',
    'transaction_type': 1,
    'transaction_date': '2_Dec_2023',
    'user_id': 'user1',
    'category_id': 'cat3',
    'synced': true,
    'local_user_id': '1a'
  },
  {
    'id': '126',
    'amount': 8,
    'currency_type': 'khr',
    'note': 'Pizza',
    'transaction_type': 1,
    'transaction_date': '5_Dec_2023',
    'user_id': 'user1',
    'category_id': 'cat5',
    'synced': true,
    'local_user_id': '1a'
  },
  {
    'id': '127',
    'amount': 18,
    'currency_type': 'khr',
    'note': 'Sushi',
    'transaction_type': 1,
    'transaction_date': '5_Dec_2023',
    'user_id': 'user1',
    'category_id': 'cat5',
    'synced': true,
    'local_user_id': '1a'
  },
  {
    'id': '129',
    'amount': 20,
    'currency_type': 'khr',
    'note': 'Pizza',
    'transaction_type': 1,
    'transaction_date': '10_Dec_2023',
    'user_id': 'user1',
    'category_id': 'cat6',
    'synced': true,
    'local_user_id': '1a'
  },
  {
    'id': '130',
    'amount': 2,
    'currency_type': 'khr',
    'note': 'Green tea',
    'transaction_type': 1,
    'transaction_date': '11_Dec_2023',
    'user_id': 'user1',
    'category_id': 'cat5',
    'synced': true,
    'local_user_id': '1a'
  },
  {
    'id': '126',
    'amount': 15,
    'currency_type': 'khr',
    'note': 'Internet fee',
    'transaction_type': 1,
    'transaction_date': '11_Dec_2023',
    'user_id': 'user1',
    'category_id': 'cat5',
    'synced': true,
    'local_user_id': '1a'
  },
];
